name: Docker Image CI

on:
  push:
    tags: [ '*' ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
      with:
        # Optionally strip `v` prefix
        strip_v: true
    - name: Build the Docker image
      run: docker build . --file "./apps/management/Dockerfile" --tag docker.io/nicholasdietz/timate_management-ui:${{steps.tag.outputs.tag}}
    - name: Docker Push
      run: docker push docker.io/nicholasdietz/timate_management-ui:${{steps.tag.outputs.tag}}
